### ISSUE TITLE
"seconds since 1970 january 1st" query crashes the app

### ISSUE THREAD

**Issue by ahmedahmedov** [mvrozanti/dte#2]
Hi, 
When I type "seconds since 1970 january 1st", the app crashes with the following stack trace: 

````
seconds since 1970 january 1st
st is not loaded
Traceback (most recent call last):
  File "/usr/local/Caskroom/miniconda/base/lib/python3.8/cmd.py", line 214, in onecmd
    func = getattr(self, 'do_' + cmd)
AttributeError: 'CmdParse' object has no attribute 'do_seconds'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Caskroom/miniconda/base/bin/dte", line 794, in p_expression_expression_point
    p[0] = datetime.combine(p[1], p[2])
TypeError: combine() argument 2 must be datetime.time, not None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Caskroom/miniconda/base/bin/dte", line 1357, in <module>
    interactive()
  File "/usr/local/Caskroom/miniconda/base/bin/dte", line 1346, in interactive
    CmdParse().cmdloop()
  File "/usr/local/Caskroom/miniconda/base/lib/python3.8/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/usr/local/Caskroom/miniconda/base/lib/python3.8/cmd.py", line 216, in onecmd
    return self.default(line)
  File "/usr/local/Caskroom/miniconda/base/bin/dte", line 1338, in default
    yacc.parse(line)
  File "/usr/local/Caskroom/miniconda/base/lib/python3.8/site-packages/ply/yacc.py", line 333, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/usr/local/Caskroom/miniconda/base/lib/python3.8/site-packages/ply/yacc.py", line 1120, in parseopt_notrack
    p.callable(pslice)
  File "/usr/local/Caskroom/miniconda/base/bin/dte", line 796, in p_expression_expression_point
    p[0] = datetime.combine(p[2], p[1])
TypeError: combine() argument 1 must be datetime.date, not None`
```

**Comment by mvrozanti** [comment]
`1970 january 1st` is currently invalid syntax, but it shouldn't be! Thanks for pointing that out. Adding this soon
