### ISSUE TITLE
Months and years can't be converted

### ISSUE THREAD

**Issue by yggdr** [mvrozanti/dte#3]
```
1M in days
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/cmd.py", line 214, in onecmd
    func = getattr(self, 'do_' + cmd)
AttributeError: 'CmdParse' object has no attribute 'do_1M'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yggdrasil/.local/bin/dte", line 1364, in <module>
    interactive()
  File "/home/yggdrasil/.local/bin/dte", line 1353, in interactive
    CmdParse().cmdloop()
  File "/usr/local/lib/python3.8/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/usr/local/lib/python3.8/cmd.py", line 216, in onecmd
    return self.default(line)
  File "/home/yggdrasil/.local/bin/dte", line 1345, in default
    yacc.parse(line)
  File "/usr/home/yggdrasil/.local/pipx/venvs/dte/lib/python3.8/site-packages/ply/yacc.py", line 333, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/usr/home/yggdrasil/.local/pipx/venvs/dte/lib/python3.8/site-packages/ply/yacc.py", line 1120, in parseopt_notrack
    p.callable(pslice)
  File "/home/yggdrasil/.local/bin/dte", line 1283, in p_statement_expression_in_unit
    p[0] = delta_to_unit(p[1], p[3].lower())
  File "/home/yggdrasil/.local/bin/dte", line 1196, in delta_to_unit
    total_seconds = delta.total_seconds()
AttributeError: 'relativedelta' object has no attribute 'total_seconds'
```

```
1s in years
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/cmd.py", line 214, in onecmd
    func = getattr(self, 'do_' + cmd)
AttributeError: 'CmdParse' object has no attribute 'do_1s'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yggdrasil/.local/bin/dte", line 1364, in <module>
    interactive()
  File "/home/yggdrasil/.local/bin/dte", line 1353, in interactive
    CmdParse().cmdloop()
  File "/usr/local/lib/python3.8/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/usr/local/lib/python3.8/cmd.py", line 216, in onecmd
    return self.default(line)
  File "/home/yggdrasil/.local/bin/dte", line 1345, in default
    yacc.parse(line)
  File "/usr/home/yggdrasil/.local/pipx/venvs/dte/lib/python3.8/site-package
s/ply/yacc.py", line 333, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/usr/home/yggdrasil/.local/pipx/venvs/dte/lib/python3.8/site-package
s/ply/yacc.py", line 1120, in parseopt_notrack
    p.callable(pslice)
  File "/home/yggdrasil/.local/bin/dte", line 1283, in p_statement_expressio
n_in_unit
    p[0] = delta_to_unit(p[1], p[3].lower())
  File "/home/yggdrasil/.local/bin/dte", line 1208, in delta_to_unit
    raise Exception('Invalid conversion')
Exception: Invalid conversion
```

**Comment by mvrozanti** [comment]
That's because those conversions are kind of controversial. Not all months have the same quantity of days. Leap years also make `1s in years` conversion indeterminable in an absolute way.

I think the best solution for this problem would be having a configuration for what one defines as a month and use that when there's margin for ambiguity, such as these two cases. What would you expect for output in this case?
